ds_course = [['Machine Learning Crash Course by Google [Free]', 'https://developers.google.com/machine-learning/crash-course'],
             ['Machine Learning A-Z by Udemy','https://www.udemy.com/course/machinelearning/'],
             ['Machine Learning by Andrew NG','https://www.coursera.org/learn/machine-learning'],
             ['Data Scientist Master Program of Simplilearn (IBM)','https://www.simplilearn.com/big-data-and-analytics/senior-data-scientist-masters-program-training'],
             ['Data Science Foundations: Fundamentals by LinkedIn','https://www.linkedin.com/learning/data-science-foundations-fundamentals-5'],
             ['Data Scientist with Python','https://www.datacamp.com/tracks/data-scientist-with-python'],
             ['Programming for Data Science with Python','https://www.udacity.com/course/programming-for-data-science-nanodegree--nd104'],
             ['Programming for Data Science with R','https://www.udacity.com/course/programming-for-data-science-nanodegree-with-R--nd118'],
             ['Introduction to Data Science','https://www.udacity.com/course/introduction-to-data-science--cd0017'],
             ['Intro to Machine Learning with TensorFlow','https://www.udacity.com/course/intro-to-machine-learning-with-tensorflow-nanodegree--nd230']]

web_course = [['Django Crash course [Free]','https://youtu.be/e1IyzVyrLSU'],
              ['Python and Django Full Stack Web Developer Bootcamp','https://www.udemy.com/course/python-and-django-full-stack-web-developer-bootcamp'],
              ['React Crash Course [Free]','https://youtu.be/Dorf8i6lCuk'],
              ['ReactJS Project Development Training','https://www.dotnettricks.com/training/masters-program/reactjs-certification-training'],
              ['Full Stack Web Developer - MEAN Stack','https://www.simplilearn.com/full-stack-web-developer-mean-stack-certification-training'],
              ['Node.js and Express.js [Free]','https://youtu.be/Oe421EPjeBE'],
              ['Flask: Develop Web Applications in Python','https://www.educative.io/courses/flask-develop-web-applications-in-python'],
              ['Full Stack Web Developer by Udacity','https://www.udacity.com/course/full-stack-web-developer-nanodegree--nd0044'],
              ['Front End Web Developer by Udacity','https://www.udacity.com/course/front-end-web-developer-nanodegree--nd0011'],
              ['Become a React Developer by Udacity','https://www.udacity.com/course/react-nanodegree--nd019']]

android_course = [['Android Development for Beginners [Free]','https://youtu.be/fis26HvvDII'],
                  ['Android App Development Specialization','https://www.coursera.org/specializations/android-app-development'],
                  ['Associate Android Developer Certification','https://grow.google/androiddev/#?modal_active=none'],
                  ['Become an Android Kotlin Developer by Udacity','https://www.udacity.com/course/android-kotlin-developer-nanodegree--nd940'],
                  ['Android Basics by Google','https://www.udacity.com/course/android-basics-nanodegree-by-google--nd803'],
                  ['The Complete Android Developer Course','https://www.udemy.com/course/complete-android-n-developer-course/'],
                  ['Building an Android App with Architecture Components','https://www.linkedin.com/learning/building-an-android-app-with-architecture-components'],
                  ['Android App Development Masterclass using Kotlin','https://www.udemy.com/course/android-oreo-kotlin-app-masterclass/'],
                  ['Flutter & Dart - The Complete Flutter App Development Course','https://www.udemy.com/course/flutter-dart-the-complete-flutter-app-development-course/'],
                  ['Flutter App Development Course [Free]','https://youtu.be/rZLR5olMR64']]

ios_course = [['IOS App Development by LinkedIn','https://www.linkedin.com/learning/subscription/topics/ios'],
              ['iOS & Swift - The Complete iOS App Development Bootcamp','https://www.udemy.com/course/ios-13-app-development-bootcamp/'],
              ['Become an iOS Developer','https://www.udacity.com/course/ios-developer-nanodegree--nd003'],
              ['iOS App Development with Swift Specialization','https://www.coursera.org/specializations/app-development'],
              ['Mobile App Development with Swift','https://www.edx.org/professional-certificate/curtinx-mobile-app-development-with-swift'],
              ['Swift Course by LinkedIn','https://www.linkedin.com/learning/subscription/topics/swift-2'],
              ['Objective-C Crash Course for Swift Developers','https://www.udemy.com/course/objectivec/'],
              ['Learn Swift by Codecademy','https://www.codecademy.com/learn/learn-swift'],
              ['Swift Tutorial - Full Course for Beginners [Free]','https://youtu.be/comQ1-x2a1Q'],
              ['Learn Swift Fast - [Free]','https://youtu.be/FcsY1YPBwzQ']]
uiux_course = [['Google UX Design Professional Certificate','https://www.coursera.org/professional-certificates/google-ux-design'],
               ['UI / UX Design Specialization','https://www.coursera.org/specializations/ui-ux-design'],
               ['The Complete App Design Course - UX, UI and Design Thinking','https://www.udemy.com/course/the-complete-app-design-course-ux-and-ui-design/'],
               ['UX & Web Design Master Course: Strategy, Design, Development','https://www.udemy.com/course/ux-web-design-master-course-strategy-design-development/'],
               ['The Complete App Design Course - UX, UI and Design Thinking','https://www.udemy.com/course/the-complete-app-design-course-ux-and-ui-design/'],
               ['DESIGN RULES: Principles + Practices for Great UI Design','https://www.udemy.com/course/design-rules/'],
               ['Become a UX Designer by Udacity','https://www.udacity.com/course/ux-designer-nanodegree--nd578'],
               ['Adobe XD Tutorial: User Experience Design Course [Free]','https://youtu.be/68w2VwalD5w'],
               ['Adobe XD for Beginners [Free]','https://youtu.be/WEljsc2jorI'],
               ['Adobe XD in Simple Way','https://learnux.io/course/adobe-xd']]
cloud_course = [['AWS Certified Solutions Architect - Associate by A Cloud Guru', 'https://acloudguru.com/course/aws-certified-solutions-architect-associate-saa-c02'],
              ['Google Cloud Platform Fundamentals: Core Infrastructure', 'https://www.coursera.org/learn/gcp-fundamentals'],
              ['Microsoft Azure Fundamentals (AZ-900) Certification Course', 'https://www.udemy.com/course/microsoft-azure-fundamentals-az-900-certification-course/'],
              ['Cloud Computing Specialization by University of Illinois', 'https://www.coursera.org/specializations/cloud-computing'],
              ['Cloud Architecture with Google Cloud Professional Certificate', 'https://www.coursera.org/professional-certificates/gcp-cloud-architect'],
              ['AWS Certified Developer - Associate Course [Free]', 'https://youtu.be/RrKRN9zRBWs'],
              ['Kubernetes for the Absolute Beginners', 'https://www.udemy.com/course/learn-kubernetes/'],
              ['Docker and Kubernetes: The Complete Guide', 'https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/'],
              ['Terraform for AWS - Beginner to Advanced', 'https://www.udemy.com/course/terraform-for-aws-with-sre-iac-devops-real-world-demos/'],
              ['Cloud Engineer Nanodegree by Udacity', 'https://www.udacity.com/course/cloud-dev-ops-nanodegree--nd9991']]

backend_course = [['Node.js API Masterclass With Express & MongoDB', 'https://www.udemy.com/course/nodejs-api-masterclass/'],
                 ['The Complete Node.js Developer Course', 'https://www.udemy.com/course/the-complete-nodejs-developer-course-2/'],
                 ['Spring Framework 5: Beginner to Guru', 'https://www.udemy.com/course/spring-framework-5-beginner-to-guru/'],
                 ['Java Programming Masterclass covering Java 11 & Java 17', 'https://www.udemy.com/course/java-the-complete-java-developer-course/'],
                 ['Python Django - The Complete Course [Free]', 'https://youtu.be/PtQiiknWUcI'],
                 ['Complete SQL and Databases Bootcamp', 'https://www.udemy.com/course/complete-sql-databases-bootcamp-zero-to-mastery/'],
                 ['FastAPI - The Complete Course', 'https://www.udemy.com/course/fastapi-the-complete-course/'],
                 ['Ruby on Rails for Beginners', 'https://www.codecademy.com/learn/learn-ruby-on-rails'],
                 ['ASP.NET Core 6 Web API Fundamentals', 'https://www.pluralsight.com/courses/asp-dot-net-core-6-web-api-fundamentals'],
                 ['GraphQL by Example', 'https://www.udemy.com/course/graphql-by-example/']]

cybersecurity_course = [['CompTIA Security+ Certification Course', 'https://www.udemy.com/course/securityplus/'],
                        ['Practical Ethical Hacking - The Complete Course', 'https://www.udemy.com/course/practical-ethical-hacking/'],
                        ['Web Security & Bug Bounty: Learn Penetration Testing', 'https://www.udemy.com/course/web-security-bug-bounty-learn-penetration-testing/'],
                        ['Certified Ethical Hacker (CEH) by EC-Council', 'https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/'],
                        ['Cybersecurity Specialization by University of Maryland', 'https://www.coursera.org/specializations/cyber-security'],
                        ['The Complete Cyber Security Course: Hackers Exposed', 'https://www.udemy.com/course/the-complete-internet-security-privacy-course-volume-1/'],
                        ['Learn Ethical Hacking From Scratch [Free]', 'https://youtu.be/3Kq1MIfTWCE'],
                        ['Mobile Security: Reverse Engineering for Android Apps', 'https://www.linkedin.com/learning/mobile-security-reverse-engineering-for-android-apps'],
                        ['CISSP Certification: Complete CISSP Course', 'https://www.udemy.com/course/cissp-certification-training-complete-cissp-prep-course/'],
                        ['Cyber Security Nanodegree by Udacity', 'https://www.udacity.com/course/security-analyst-nanodegree--nd335']]

ai_engineering_course = [['Deep Learning Specialization by Andrew NG', 'https://www.coursera.org/specializations/deep-learning'],
                         ['Artificial Intelligence: Reinforcement Learning in Python', 'https://www.udemy.com/course/artificial-intelligence-reinforcement-learning-in-python/'],
                         ['Natural Language Processing with Deep Learning', 'https://www.coursera.org/learn/nlp-with-deep-learning'],
                         ['TensorFlow Developer Certificate in 2023: Zero to Mastery', 'https://www.udemy.com/course/tensorflow-developer-certificate-machine-learning-zero-to-mastery/'],
                         ['AI For Everyone by Andrew NG [Free]', 'https://www.coursera.org/learn/ai-for-everyone'],
                         ['PyTorch for Deep Learning with Python Bootcamp', 'https://www.udemy.com/course/pytorch-for-deep-learning-with-python-bootcamp/'],
                         ['Complete Guide to Transformers and Large Language Models', 'https://www.deeplearning.ai/courses/transformers-and-large-language-models/'],
                         ['AI Product Manager Nanodegree by Udacity', 'https://www.udacity.com/course/ai-product-manager-nanodegree--nd088'],
                         ['Practical Deep Learning for Coders by fast.ai [Free]', 'https://course.fast.ai/'],
                         ['Hugging Face NLP Course [Free]', 'https://huggingface.co/course/chapter1/1']]
resume_videos = []

interview_videos = []